### ISSUE TITLE
模块不生效，userid获取失败

### ISSUE THREAD

**Issue by airectx** [nining377/dolby_beta#178]
使用网易云6.40，magisk+lsposed，MIUI12.0.10
Lsp日志
```
----part 1 start----
[ 2021-12-06T20:31:49.277    10269: 10046: 10046 I/LSPosed-Bridge  ] Loading module com.raincat.dolby_beta from /data/app/com.raincat.dolby_beta-66dFfcXhUj6VCRYCKrFzoQ==/base.apk
[ 2021-12-06T20:31:49.329    10269: 10046: 10046 I/LSPosed-Bridge  ]   Loading class com.raincat.dolby_beta.MainHook
[ 2021-12-06T20:31:49.476    10269: 10046: 10046 E/LSPosed-Bridge  ] de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: okhttp3.internal.connection.RealCall
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:13)
	at com.raincat.dolby_beta.hook.ProxyHook.<init>(ProxyHook.java:66)
	at com.raincat.dolby_beta.Hook$1.afterHookedMethod(Hook.java:86)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.attachBaseContext(Unknown Source:11)
	at bin.mt.apksignaturekillerplus.HookApplication.attachBaseContext(Unknown Source:3)
	at android.app.Application.attach(Application.java:376)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1156)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1222)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6595)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1400(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:7604)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
Caused by: java.lang.ClassNotFoundException: okhttp3.internal.connection.RealCall
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at A0.a(Unknown Source:24)
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:5)
	... 20 more
Caused by: java.lang.ClassNotFoundException: okhttp3.internal.connection.RealCall
	... 24 more
[ 2021-12-06T20:31:49.828    10269: 10115: 10115 I/LSPosed-Bridge  ] Loading module com.raincat.dolby_beta from /data/app/com.raincat.dolby_beta-66dFfcXhUj6VCRYCKrFzoQ==/base.apk
[ 2021-12-06T20:31:49.890    10269: 10115: 10115 I/LSPosed-Bridge  ]   Loading class com.raincat.dolby_beta.MainHook
[ 2021-12-06T20:31:49.903    10269: 10133: 10133 I/LSPosed-Bridge  ] Loading module com.raincat.dolby_beta from /data/app/com.raincat.dolby_beta-66dFfcXhUj6VCRYCKrFzoQ==/base.apk
[ 2021-12-06T20:31:49.951    10269: 10133: 10133 I/LSPosed-Bridge  ]   Loading class com.raincat.dolby_beta.MainHook
[ 2021-12-06T20:31:49.959    10269: 10152: 10152 I/LSPosed-Bridge  ] Loading module com.raincat.dolby_beta from /data/app/com.raincat.dolby_beta-66dFfcXhUj6VCRYCKrFzoQ==/base.apk

**Comment by nining377** [comment]
把清洁工关掉

**Comment by nining377** [comment]
你使用了改版网易云，不能适配

**Comment by airectx** [comment]
> 你使用了改版网易云，不能适配

谢谢！好像是用了改版
