### ISSUE TITLE
8.9.50自动签到闪退

### ISSUE THREAD

**Issue by natsumerinchan** [nining377/dolby_beta#321]
如题，我在8.9.50开启了自动签到导致网易云一直闪退，我尝试卸载重装模块以及清了网易云所有数据但问题依旧

![Screenshot_20230314-230848_Pixel 启动器](https://user-images.githubusercontent.com/64072399/225046645-1d849e38-1ee9-4734-ab8f-f9d125e3ef2c.png)

[logcat.log](https://github.com/nining377/dolby_beta/files/10970297/logcat.log)

**Comment by kmiit** [comment]
我直接一装上就开始闪退了，连续点几次直接自动清除数据了。。。（MIUI14.0.23.3.7.dev，用的刚刚最新的action版）
也是找不到cookie类
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.reflect.Method[] java.lang.Class.getDeclaredMethods()' on a null object reference
	at de.robv.android.xposed.XposedHelpers.findMethodsByExactParameters(Unknown Source:5)
	at com.raincat.dolby_beta.helper.ClassHelper$Cookie.getCookie(ClassHelper.java:171)
	at com.raincat.dolby_beta.hook.UserProfileHook$2.lambda$afterHookedMethod$0(UserProfileHook.java:52)
	at com.raincat.dolby_beta.hook.-$$Lambda$UserProfileHook$2$xE5tYMS3sZAcBvdQ-B3YwSyw3G8.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)
