### ISSUE TITLE
最新版网易云LSPosed启用模块后闪退

### ISSUE THREAD

**Issue by Snigellin** [nining377/dolby_beta#347]
应用名称：网易云音乐
应用版本：8.10.61
问题发生时间：2023-09-06 17:01:05
问题Trace：
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.reflect.Method[] java.lang.Class.getDeclaredMethods()' on a null object reference
	at de.robv.android.xposed.XposedHelpers.findMethodsByExactParameters(Unknown Source:5)
	at com.raincat.dolby_beta.helper.ClassHelper$Cookie.getCookie(ClassHelper.java:171)
	at com.raincat.dolby_beta.hook.UserProfileHook$2.lambda$afterHookedMethod$0(UserProfileHook.java:52)
	at com.raincat.dolby_beta.hook.-$$Lambda$UserProfileHook$2$xE5tYMS3sZAcBvdQ-B3YwSyw3G8.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by mario6714** [comment]
Maybe this can help you to fix the error:

https://github.com/nining377/dolby_beta/actions/runs/5941812196
